<!DOCTYPE html>
<html lang="en" >
<head>
	<meta charset="utf-8">
	<title>Promise chain</title>
</head>
<body>
	<pre>Console output only</pre>
	<script type="module">

		// Test to check how errors are 'catched' in async / Promises.
		// https://javascript.info/async-await
		// http://thecodebarbarian.com/async-await-error-handling-in-javascript.html
		async function a() {
			const a = 0
			a = 1 // <-- Syntax error
			return 'b'
		}

		console.log('a')
		a().then(res => {console.log(res)}).catch(err => {console.log(err)})
		console.log('c')

	</script>

</body>
</html>